import React, { useState } from 'react';
import { 
  ShieldAlert, 
  CheckCircle,
  AlertTriangle,
  Sliders,
  Download
} from 'lucide-react';
import { useCase } from '../hooks/useCase';
import { useToast } from '../hooks/useToast';
import { calculateForensicRiskScore } from '../utils/riskScoring';
import { downloadText } from '../utils/download';

export default function RiskAnalyzer() {
  const { activeCase } = useCase();
  const { showToast } = useToast();

  const [mixerWeight, setMixerWeight] = useState(35);
  const [hopWeight, setHopWeight] = useState(12);
  const [kycDiscountWeight, setKycDiscountWeight] = useState(15);
  const [showConfig, setShowConfig] = useState(false);

  if (!activeCase) return <div style={{ color: 'var(--text-secondary)' }}>Select a case first.</div>;

  const assessment = calculateForensicRiskScore(activeCase, {
    mixerWeight,
    hopWeight,
    kycDiscountWeight
  });

  const {
    riskScore: calculatedRiskScore,
    isHistoricalEra,
    isKycVerified,
    threatBadge,
    dimensions,
    threatSignatures: riskFactors,
    statutoryAction
  } = assessment;

  const {
    obfuscationScore,
    layeringScore,
    destinationScore,
    velocityScore
  } = dimensions;

  const handleExportDossier = () => {
    const reportText = `NCB BLOCKCHAIN FORENSIC THREAT ASSESSMENT DOSSIER
======================================================
Case Reference: ${activeCase.id.toUpperCase()} - ${activeCase.title}
Date of Evaluation: ${new Date().toISOString()}
Cryptocurrency Asset: ${activeCase.currency} Protocol
Investigated Nodes: ${activeCase.nodes.length}

DYNAMIC RISK SCORE: ${calculatedRiskScore} / 100 [${threatBadge.label}]
------------------------------------------------------
DIMENSIONAL BREAKDOWN:
- Obfuscation & Mixer Index: ${obfuscationScore}%
- Layering Peeling Chain Index: ${layeringScore}%
- Destination KYC Attribution: ${isKycVerified ? 'MITIGATED (KYC Active)' : isHistoricalEra ? 'HISTORICAL P2P' : 'UNMITIGATED'} (${destinationScore}%)
- Network Velocity Risk: ${velocityScore}%

HEURISTIC RISK SIGNATURES:
${riskFactors.map(rf => `[${rf.status.toUpperCase()}] ${rf.name} (${rf.score})\n  Category: ${rf.category}\n  Details: ${rf.description}`).join('\n\n')}

RECOMMENDED INVESTIGATIVE ACTION (${statutoryAction.urgency}):
${statutoryAction.recommendations.map((rec, i) => `${i + 1}. ${rec}`).join('\n')}
======================================================
Generated by AegisTrace NCB Intelligence Terminal`;

    downloadText(reportText, `NCB-Risk-Dossier-${activeCase.id.toUpperCase()}.txt`);
    showToast("Downloaded Forensic Risk Dossier file.", "success");
  };

  return (
    <div style={{ display: 'grid', gridTemplateColumns: '3fr 2fr', gap: '1.5rem' }}>
      
      {/* Risk Metrics Table */}
      <div className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', gap: '1.25rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: '0.5rem' }}>
          <div>
            <h3 style={{ fontSize: '1.25rem', fontWeight: 600, display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
              <ShieldAlert style={{ color: 'var(--risk-high)' }} /> Dynamic Graph Risk Analysis
            </h3>
            <p style={{ color: 'var(--text-secondary)', fontSize: '0.85rem' }}>
              Evaluates graph pathing, peeling chain hop depth, mixer interactions, and end receiver settlement properties.
            </p>
          </div>

          <div style={{ display: 'flex', gap: '0.4rem' }}>
            <button
              onClick={() => setShowConfig(!showConfig)}
              className={`btn ${showConfig ? 'btn-primary' : 'btn-outline'}`}
              style={{ fontSize: '0.75rem', padding: '0.3rem 0.6rem' }}
            >
              <Sliders size={13} /> {showConfig ? "Hide Weights" : "Adjust Weights"}
            </button>
            <button
              onClick={handleExportDossier}
              className="btn"
              style={{ fontSize: '0.75rem', padding: '0.3rem 0.6rem' }}
              title="Download Formatted Risk Assessment Dossier"
            >
              <Download size={13} /> Dossier
            </button>
          </div>
        </div>

        {/* Weights Configuration Panel */}
        {showConfig && (
          <div style={{ backgroundColor: 'rgba(5, 8, 16, 0.8)', padding: '1rem', borderRadius: '8px', border: '1px solid var(--border-color)', display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: '1rem' }}>
            <div>
              <label style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.25rem' }}>Mixer Weight: {mixerWeight}%</label>
              <input 
                type="range" 
                min="10" 
                max="50" 
                value={mixerWeight} 
                onChange={(e) => setMixerWeight(Number(e.target.value))}
                style={{ width: '100%' }}
              />
            </div>
            <div>
              <label style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.25rem' }}>Hop Peeling Weight: {hopWeight}%</label>
              <input 
                type="range" 
                min="5" 
                max="25" 
                value={hopWeight} 
                onChange={(e) => setHopWeight(Number(e.target.value))}
                style={{ width: '100%' }}
              />
            </div>
            <div>
              <label style={{ fontSize: '0.7rem', color: 'var(--text-secondary)', display: 'block', marginBottom: '0.25rem' }}>KYC Discount: -{kycDiscountWeight}%</label>
              <input 
                type="range" 
                min="5" 
                max="30" 
                value={kycDiscountWeight} 
                onChange={(e) => setKycDiscountWeight(Number(e.target.value))}
                style={{ width: '100%' }}
              />
            </div>
          </div>
        )}

        {/* 4-Dimensional Progress Breakdown */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '0.75rem' }}>
          <div style={{ backgroundColor: 'rgba(5, 8, 16, 0.6)', padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', marginBottom: '0.3rem' }}>
              <span style={{ color: 'var(--text-secondary)' }}>Obfuscation / Mixer Risk</span>
              <strong style={{ color: obfuscationScore > 25 ? '#ef4444' : '#f59e0b' }}>{obfuscationScore}%</strong>
            </div>
            <div style={{ width: '100%', height: '5px', backgroundColor: '#1e293b', borderRadius: '3px', overflow: 'hidden' }}>
              <div style={{ width: `${Math.min(100, obfuscationScore * 2)}%`, height: '100%', backgroundColor: obfuscationScore > 25 ? '#ef4444' : '#f59e0b' }}></div>
            </div>
          </div>

          <div style={{ backgroundColor: 'rgba(5, 8, 16, 0.6)', padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', marginBottom: '0.3rem' }}>
              <span style={{ color: 'var(--text-secondary)' }}>Layering Hop Peeling</span>
              <strong style={{ color: layeringScore > 20 ? '#ef4444' : '#10b981' }}>{layeringScore}%</strong>
            </div>
            <div style={{ width: '100%', height: '5px', backgroundColor: '#1e293b', borderRadius: '3px', overflow: 'hidden' }}>
              <div style={{ width: `${Math.min(100, layeringScore * 2.5)}%`, height: '100%', backgroundColor: layeringScore > 20 ? '#ef4444' : '#10b981' }}></div>
            </div>
          </div>

          <div style={{ backgroundColor: 'rgba(5, 8, 16, 0.6)', padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', marginBottom: '0.3rem' }}>
              <span style={{ color: 'var(--text-secondary)' }}>Destination KYC Exposure</span>
              <strong style={{ color: isKycVerified ? '#10b981' : '#f59e0b' }}>{destinationScore}%</strong>
            </div>
            <div style={{ width: '100%', height: '5px', backgroundColor: '#1e293b', borderRadius: '3px', overflow: 'hidden' }}>
              <div style={{ width: `${Math.min(100, destinationScore * 2.5)}%`, height: '100%', backgroundColor: isKycVerified ? '#10b981' : '#f59e0b' }}></div>
            </div>
          </div>

          <div style={{ backgroundColor: 'rgba(5, 8, 16, 0.6)', padding: '0.75rem', borderRadius: '6px', border: '1px solid var(--border-color)' }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '0.75rem', marginBottom: '0.3rem' }}>
              <span style={{ color: 'var(--text-secondary)' }}>Network Velocity Metric</span>
              <strong style={{ color: '#0ea5e9' }}>{velocityScore}%</strong>
            </div>
            <div style={{ width: '100%', height: '5px', backgroundColor: '#1e293b', borderRadius: '3px', overflow: 'hidden' }}>
              <div style={{ width: `${Math.min(100, velocityScore * 4)}%`, height: '100%', backgroundColor: '#0ea5e9' }}></div>
            </div>
          </div>
        </div>

        {/* Risk Factors List */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: '0.75rem' }}>
          {riskFactors.map((rf, i) => (
            <div 
              key={i} 
              style={{ 
                padding: '0.9rem', 
                borderRadius: '8px', 
                backgroundColor: 'rgba(255,255,255,0.02)', 
                border: '1px solid var(--border-color)',
                display: 'flex',
                justifyContent: 'space-between',
                alignItems: 'center'
              }}
            >
              <div>
                <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
                  {rf.status === 'detected' ? (
                    <AlertTriangle size={16} style={{ color: 'var(--risk-medium)' }} />
                  ) : (
                    <CheckCircle size={16} style={{ color: 'var(--risk-low)' }} />
                  )}
                  <h4 style={{ fontSize: '0.9rem', fontWeight: 600 }}>{rf.name}</h4>
                  <span style={{ fontSize: '0.65rem', color: 'var(--text-muted)', backgroundColor: 'rgba(255,255,255,0.05)', padding: '0.1rem 0.4rem', borderRadius: '4px' }}>
                    {rf.category}
                  </span>
                </div>
                <p style={{ color: 'var(--text-muted)', fontSize: '0.75rem', marginTop: '0.25rem' }}>{rf.description}</p>
              </div>
              <div style={{ textAlign: 'right' }}>
                <span style={{ 
                  fontSize: '0.9rem', 
                  fontWeight: 700, 
                  color: rf.status === 'detected' ? 'var(--risk-high)' : 'var(--risk-low)' 
                }}>
                  {rf.score}
                </span>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* Dynamic Gauge Panel */}
      <div className="glass-panel" style={{ padding: '1.5rem', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '1rem' }}>
        <h4 style={{ fontSize: '1rem', fontWeight: 600, color: 'var(--text-secondary)', textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          Aggregate Risk Index
        </h4>

        {/* Circular Risk Meter */}
        <div style={{ position: 'relative', width: '180px', height: '180px', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
          <svg width="180" height="180" viewBox="0 0 100 100">
            <circle cx="50" cy="50" r="40" fill="none" stroke="#1e293b" strokeWidth="8" />
            <circle 
              cx="50" 
              cy="50" 
              r="40" 
              fill="none" 
              stroke={calculatedRiskScore > 75 ? '#ef4444' : calculatedRiskScore > 50 ? '#f59e0b' : '#10b981'} 
              strokeWidth="8"
              strokeDasharray="251.2"
              strokeDashoffset={251.2 - (251.2 * calculatedRiskScore) / 100}
              strokeLinecap="round"
              transform="rotate(-90 50 50)"
              style={{ transition: 'stroke-dashoffset 0.6s ease-in-out' }}
            />
          </svg>
          <div style={{ position: 'absolute', textAlign: 'center' }}>
            <span style={{ fontSize: '2.4rem', fontWeight: 800, color: '#fff', display: 'block' }}>{calculatedRiskScore}</span>
            <span style={{ fontSize: '0.7rem', color: 'var(--text-muted)', textTransform: 'uppercase' }}>out of 100</span>
          </div>
        </div>

        <div style={{ textAlign: 'center', marginTop: '0.5rem' }}>
          <span style={{ 
            fontSize: '0.8rem', 
            fontWeight: 600, 
            padding: '0.25rem 0.6rem', 
            borderRadius: '4px',
            backgroundColor: threatBadge.bg,
            color: threatBadge.color,
            textTransform: 'uppercase'
          }}>
            {threatBadge.label}
          </span>
          <p style={{ color: 'var(--text-muted)', fontSize: '0.75rem', marginTop: '0.75rem', maxWidth: '280px' }}>
            {calculatedRiskScore >= 70 
              ? "Critical risk indicators detected. Escalation recommended for statutory notice issuance."
              : calculatedRiskScore >= 35
              ? "Moderate exposure detected. On-chain monitoring and exchange attribution suggested."
              : "Standard benign/historical flow. Clean transaction structure with no mixing signatures."}
          </p>
        </div>
      </div>

    </div>
  );
}
